---
# ansible_playbook_host/playboos/boreas.yml
# Author: MTO
# Description: Boreas file for ansible_playbook_host
#
- name: "BOREAS"
  hosts: targets
 
  vars:
    dump_vars: true

  pre_tasks:
    - name: Test Ansible ping
      ping:

    - name: Run a command to get target release
      shell: cat /etc/*ease || sw_vers
      changed_when: false

  roles:
    - { role: vendors/linux-system-roles/network, tags: network, system }
    - { role: vendors/linux-system-roles/timesync, tags: timesync, system }
    - { role: mto79/system/upgrade, tags: upgrade, system }