---
# ansible_playbook_host/playbooks/boreas.yml
# Author: MTO
# Description: Boreas file for ansible_playbook_host
#
- name: "HOST: Boreas"
  hosts: boreas
 
  vars_files:
    - vars/main.yml

  roles:
    - { role: vendors/linux-system-roles/network, tags: network, system }
    - { role: vendors/linux-system-roles/kernel_settings, tags: ['kernel', 'system'] }
    - { role: vendors/linux-system-roles/selinux, tags: selinux, system }
    - { role: vendors/linux-system-roles/timesync, tags: timesync, system }
    - { role: mto79/system/upgrade, tags: upgrade, system }